name: 'GTA'
description: 'Finds Go packages that have deviated from their upstream source.'

inputs:
  base:
    description: 'Base branch to diff against'
    required: false
    default: 'origin/master'
  include:
    description: 'Define changes to be filtered with a set of comma-separated prefixes'
    required: false
    default: ''
  merge:
    description: 'Diff using the latest merge commit'
    required: false
    default: false
  json:
    description: 'Output list of changes as JSON'
    required: false
    default: false
  buildable_only:
    description: 'Keep buildable changed packages only'
    required: false
    default: true
  changed_files:
    description: 'Path to a file containing a newline-separated list of files that have changed'
    required: false
    default: ''
  tags:
    description: 'A list of build tags to consider'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install Go package
      shell: bash
      # todo nickyd: update to current stable version tag
      run: go install github.com/digitalocean/gta/cmd/gta@latest

    - name: Run GTA
      shell: bash
      run: |
        which gta
        
        changedFilesFlag=""
        if [[ -n "${{ inputs.changed_files }}" ]]; then
          changedFilesFlag="-changed-files ${{ inputs.changed_files }}"
        fi

        gta \
          -base "${{ inputs.base }}" \

        changed_packages=$(gta \
          -base "${{ inputs.base }}" \

        echo "changed packages:"
        echo "${changed_packages}"
        echo "${changed_packages}" > $GITHUB_OUTPUT
        echo "changed_packages=${changed_packages}" >> $GITHUB_ENV

outputs:
  changed_packages:
    description: 'A newline-delimited list of packages that have deviated from the given base'

branding:
  icon: 'package'
  color: 'blue'
