name: test
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go: ['1.23','1.24']
    steps:
    - name: setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: $GITHUB_WORKSPACE/scripts/ci.sh
