name: Test GTA Action

on:
  pull_request:
    paths:
      - 'action.yaml'
      - 'entrypoint.sh'
      - 'Dockerfile'
      - '**/*.go'

jobs:
  test-action:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup test git Repository
        run: |
          echo "Creating repo in ./test-repo"
          mkdir -p ./test-repo/src
          cp -r ./testdata/* ./test-repo/src
          cd ./test-repo

          # Initialize a new Git repository with the master branch
          git init -b master

          # Configure Git user and email
          git config user.email "gtatest@example.com"
          git config user.name "gta test"

          # Add a dummy file to the repository
          echo "Initial content" > src/dummy.txt
          git add src

          # Commit the changes
          git commit -m "initial commit"

          # Create origin/master branch to simulate a remote
          git branch origin/master

          # Create origin/feature-branch branch to simulate a non-master remote
          git checkout -b origin/feature-branch

          echo "\nconst baz = \"buzz\"\n" >> ./src/gtatest/foo/foo.go
          
          git add .

          git commit -m "update pkg foo"

          echo "Repository setup successful."

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run GTA Action
        id: gta
        uses: ./
        with:
          base: 'origin/main'
          include: 'example_prefix'
          merge: 'true'
          json: 'true'
          buildable_only: 'false'
          changed_files: 'example_changed_files.txt'
          tags: 'example_tag'

      - name: Validate output
        run: |
          echo "Changed packages:"
          echo "${{ steps.gta.outputs.changed_packages }}"
