name: Test GTA Action

on:
  pull_request:
    paths:
      - 'action.yaml'
      - 'entrypoint.sh'
      - 'Dockerfile'
      - '**/*.go'

jobs:
  test-action:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup test git Repository
        run: |
          echo "Creating repo in ./test-repo"
          mkdir -p ./test-repo/src
          cp -r ./testdata/* ./test-repo/src

          cd ./test-repo/src/gtatest

          go mod init gta.test
          go mod tidy

          # Initialize a new Git repository with the master branch
          git init -b master

          # Configure Git user and email
          git config user.email "gtatest@example.com"
          git config user.name "gta test"

          # Add a dummy file to the repository
          echo "Initial content" > dummy.txt
          git add .

          # Commit the changes
          git commit -m "initial commit"

          # Create origin/master branch to simulate a remote
          git branch origin/master

          # Create a feature branch with changes
          git checkout -b origin/feature-branch

          echo "\nconst baz = \"buzz\"\n" >> foo/foo.go
          
          git add .

          git commit -m "update pkg foo"

          echo "Repository setup successful."

      - name: Run GTA Action
        id: gta
        uses: ./
        with:
          json: true

      - name: Validate output
        run: |
          echo "Changed packages:"
          echo "${{ steps.gta.outputs.changed_packages }}"
